Backend/CreateChangeLogForDatabaseStructure
nromanen/Schedule pull request #187
Opened 2022-01-22 17:23 UTC by SaneQQQQ

2022-01-27 22:01 UTC, dshma requested changes
I'd also rename the file to **initial-schema** instead of _start_database_structure_.

2022-01-27 22:01 UTC, dshma commented on src/main/resources/db/changelog/start_database_structure_changelog.yaml
> +    author: SaneQQQQ (generated)
there is no need to keep the (generated) part, let's get rid of it

2022-01-27 23:31 UTC, dshma commented
BTW:
I haven't seen any sequence being created as part of the initial schema, which is a bit queer. Have you tried applying this changelog to reflect a brand new schema?

2022-01-28 10:10 UTC, SaneQQQQ commented
> BTW: I haven't seen any sequence being created as part of the initial schema, which is a bit queer. Have you tried applying this changelog to reflect a brand new schema?

I find the difference between restore file and generated initial schema. Now I create all the sequences and add it to fields as default value.

2022-01-30 10:20 UTC, dshma approved these changes

2022-01-31 11:12 UTC, merged