Add CI pipeline
nromanen/Schedule pull request #217
Opened 2022-05-05 11:13 UTC by pro100user15

2022-05-07 17:03 UTC, dshma requested changes

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: actions/checkout@v2
v3 could be used

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: actions/setup-java@v1
v3 could be used, take 'temurin' distribution
https://github.com/actions/setup-java

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: actions/cache@v1
using setup-java@v3 it would look like this:
cache: 'gradle'

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: actions/cache@v1
v3 could be used

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: supercharge/mongodb-github-action@1.7.0
I think component scanning within test classes should be restricted to not checking the MongoConfig as this forces to start a MongoDB server when it is not even needed

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        uses: superchargejs/redis-github-action@1.1.0
same as for MongoDB

2022-05-07 17:03 UTC, dshma commented on .github/workflows/build.yml
> +        run: ./gradlew sonarqube -x test --info
why info logging level?

2022-05-07 19:37 UTC, pro100user15 commented on .github/workflows/build.yml
> +        run: ./gradlew sonarqube -x test --info
I looked through the logs and forgot to delete

2022-05-09 09:05 UTC, dshma commented on .github/workflows/build.yml
> +      - run: ./gradlew build --no-daemon
why running the build two times?
lines 23 and 36

2022-05-09 09:05 UTC, dshma commented on .github/workflows/build.yml
> +      - run: ./gradlew build --no-daemon
why --no-daemon?

2022-05-09 19:59 UTC, dshma commented on .github/workflows/build.yml
> -          cache: 'gradle'
why removing the cradle packages cache?

2022-05-09 20:44 UTC, dshma approved these changes

2022-05-10 11:04 UTC, merged