receiving of groups refactored
nromanen/Schedule pull request #242
Opened 2022-06-24 11:47 UTC by petrokrechunyak

2022-06-26 20:10 UTC, dshma requested changes

2022-06-26 20:10 UTC, dshma commented on frontend/.eslintrc.json
> +  "parser": "@babel/eslint-parser",
I don't think it has anything to do with this task, do create a separate one to update obsolete dependencies if needed
FYI:
https://github.com/nromanen/Schedule/issues/241

2022-06-26 20:10 UTC, dshma commented on frontend/package.json
> +        "@kenshooui/react-multi-select": "^1.0.53",
the same comment applies to the changes within this class

2022-06-26 20:10 UTC, dshma commented on frontend/src/components/Auth/Auth.js
> +                    {/*<a*/}
why comment this?

2022-06-26 20:10 UTC, dshma commented on frontend/src/constants/axios.js
> +export const GROUPS_URL = 'groups'
missing semicolon

2022-06-26 20:10 UTC, dshma commented on src/main/java/com/softserve/controller/GroupController.java
> +                .body(groupMapper.groupsToGroupDTOs(groupService.getAllBySortingOrder()));
I don't think it's a good idea to force sorting by order in any case, it should rather be a default sort if none specified

2022-06-26 20:10 UTC, dshma commented on src/main/resources/hibernate.properties
> +hibernate.connection.username=ama_user
no way this is getting committed, this is your local server's config

2022-06-26 20:10 UTC, dshma commented on src/main/resources/mail.properties
> +spring.mail.host=smtp.gmail.com
why change this?

2022-06-28 18:53 UTC, petrokrechunyak commented on src/main/resources/mail.properties
> +spring.mail.host=smtp.gmail.com
We use our own mail accounts as mail sender to students

2022-06-28 18:54 UTC, petrokrechunyak commented on src/main/java/com/softserve/controller/GroupController.java
> +                .body(groupMapper.groupsToGroupDTOs(groupService.getAllBySortingOrder()));
My task was to change default getter of groups to sorted

2022-06-28 19:01 UTC, petrokrechunyak commented on frontend/src/components/Auth/Auth.js
> +                    {/*<a*/}
Last group started to do Google authentication but didnt end, and now without commenting this link we cant go to login page

2022-07-05 19:03 UTC, dshma approved these changes

2022-07-07 08:57 UTC, merged