Created generic repository for sorting
nromanen/Schedule pull request #250
Opened 2022-07-18 13:26 UTC by petrokrechunyak

2022-07-20 21:49 UTC, dshma requested changes

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/controller/GroupController.java
>      public ResponseEntity<GroupDTO> saveGroupAfter(@RequestBody GroupOrderDTO groupDTO) {
method name is still "save"

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/controller/RoomController.java
> +        if (roomAfterId == null) {
path variable are required by default
if it is missing, an exception should be thrown, how can this parameter be null considering that?

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +    public SortOrderRepository() {
why is this constructor needed?

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +                        "SELECT (count(*) > 0)"
SELECT 1 or SELECT EXISTS could be used, I'd recommend the first approach, in that case uniqueResult() != null can be checked

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +                + "SET c.sortOrder = c.sortOrder+1 "
missing spaces

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +    private Class<?> tClass = SortOrderRepository.class;
why initialize it like this?

2022-07-20 21:49 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +    private Class<?> tClass = SortOrderRepository.class;
the setter is a bid bizarre in this case, let's follow this naming convention:
https://stackoverflow.com/questions/2529974/why-do-java-programmers-like-to-name-a-variable-clazz

2022-07-23 18:21 UTC, petrokrechunyak commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +                + "SET c.sortOrder = c.sortOrder+1 "
I can`t understand which spaces did I miss.

2022-07-25 14:25 UTC, dshma commented on src/main/java/com/softserve/repository/SortOrderRepository.java
> +                + "SET c.sortOrder = c.sortOrder+1 "
c.sortOrder+1 vs. c.sortOrder + 1

2022-07-26 10:56 UTC, dshma approved these changes

2022-07-26 12:58 UTC, merged