TS-19-v2-38: Create constants for all translation labels
nromanen/Schedule pull request #39
Opened 2021-10-12 10:23 UTC by ViktoriiaKosovan

2021-10-13 16:37 UTC, HiroFive approved these changes

2021-10-14 06:21 UTC, Akr1s requested changes

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/groupService.js
>      updateGroupService(group);
technically, `group` and `bufferGroup` link to the same object, but `update...(bufferGroup)` seems more obvious

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/groupService.js
>      updateGroupService(group);
the same as above

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/roomService.js
>      put(room);
the same like in the previous file

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/roomService.js
>      put(room);
as above

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/semesterService.js
>      putSemester(semester);
+1

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/semesterService.js
>      putSemester(semester);
+1

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/subjectService.js
>      updateSubjectService(subject);
+1

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/subjectService.js
>      updateSubjectService(subject);
+1

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/teacherService.js
>      updateTeacherService({ teacher });
+1

2021-10-14 06:21 UTC, Akr1s commented on frontend/src/services/teacherService.js
>      updateTeacherService({ teacher });
+1

2021-10-15 06:22 UTC, Akr1s approved these changes

2021-10-17 19:07 UTC, Niknikson submitted a review, later dismissed

2021-10-17 19:20 UTC, Niknikson approved these changes

2021-10-18 09:38 UTC, closed without merging