TS-19-v2-25: Fix ESLint errors in share directory
nromanen/Schedule pull request #40
Opened 2021-10-12 17:30 UTC by HiroFive

2021-10-14 06:22 UTC, Akr1s requested changes

2021-10-14 06:22 UTC, Akr1s commented on frontend/src/share/modals/modal/setDefaultDialog.js
> +            : i18n.t('common:do_you_wanna_show');
Make a separate function for reusable logic

2021-10-14 06:22 UTC, Akr1s commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +        return [];
Maybe you should return null instead?

2021-10-14 06:22 UTC, Akr1s commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +                    checkBoxStudents[index].checked = event.target.checked;
isn't `checkBoxStudents[index]` the same as `checkbox`?

2021-10-14 06:22 UTC, Akr1s commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +                checkBoxStudents[index].checked = false;
the same as above

2021-10-14 06:22 UTC, Akr1s commented on frontend/src/share/modals/modal/showStudentsDialog.js
>          }
you could use `Array.prototype.every()` instead

2021-10-14 10:35 UTC, HiroFive commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +        return [];
no because we generate options for select

2021-10-14 10:35 UTC, Niknikson approved these changes

2021-10-14 10:37 UTC, HiroFive commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +                    checkBoxStudents[index].checked = event.target.checked;
### checkBoxStudents[index] so we avoid no-param-reassign

2021-10-14 10:42 UTC, HiroFive commented on frontend/src/share/modals/modal/showStudentsDialog.js
> +                checkBoxStudents[index].checked = false;
the same

2021-10-14 11:06 UTC, HiroFive commented on frontend/src/share/modals/modal/showStudentsDialog.js
>          }
Then we won't be able to stop `every` through `break`

2021-10-14 11:08 UTC, HiroFive commented on frontend/src/share/modals/modal/setDefaultDialog.js
> +            : i18n.t('common:do_you_wanna_show');
this logic fixed in #36

2021-10-15 15:37 UTC, Akr1s approved these changes

2021-10-15 15:38 UTC, ViktoriiaKosovan approved these changes

2021-10-18 11:36 UTC, closed without merging